Update pre-merge-check.yml

diff --git a/.github/workflows/pre-merge-check.yml b/.github/workflows/pre-merge-check.yml
--- a/.github/workflows/pre-merge-check.yml
+++ b/.github/workflows/pre-merge-check.yml
@@ -1,21 +1,20 @@
-name: Pre-Merge Deployment Server Check
+name: Pre-Merge Minute Check
 
-on: 
-  pull_request_target:
-    types: [labeled]
+on:
+  pull_request:
+    types: [synchronize, opened, reopened]
 
 jobs:
-  check-deployment-server:
+  check-minute:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Check if server is available
+    - name: Check if the current minute is an even number
       run: |
-          minute=$(date +%M)
-          echo "Current minute: $minute"
-          if [ $((minute % 2)) -eq 0 ]; then
-            echo "Current minute is an even number."
-          else
-            echo "Current minute is an odd number. Aborting."
-            exit 1
-          fi
+        minute=$(date +%M)
+        echo "Current minute: $minute"
+        if [ $((minute % 2)) -eq 0 ]; then
+          echo "Current minute is an even number."
+        else
+          echo "Current minute is an odd number. Aborting."
+          exit 1
